CREATE TABLE IF NOT EXISTS site_config(id INTEGER PRIMARY KEY CHECK(id=1),site_name TEXT,logo TEXT,avatar TEXT,artist_name TEXT,artist_bio TEXT,social_links TEXT);
CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS subcategories(id INTEGER PRIMARY KEY AUTOINCREMENT,category_id INTEGER,name TEXT,UNIQUE(category_id,name));
CREATE TABLE IF NOT EXISTS periods(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT UNIQUE);
CREATE TABLE IF NOT EXISTS works(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,category_id INTEGER,subcategory_id INTEGER,work_no TEXT UNIQUE,creation_time TEXT,size TEXT,description TEXT,main_image TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS work_images(id INTEGER PRIMARY KEY AUTOINCREMENT,work_id INTEGER,filename TEXT,is_main INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'admin',display_name TEXT,created_at TEXT,updated_at TEXT);
CREATE TABLE IF NOT EXISTS operation_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,admin_id INTEGER,admin_name TEXT,action TEXT,detail TEXT,created_at TEXT);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,admin_id INTEGER NOT NULL,expires_at INTEGER NOT NULL);
