const JSON_HEADERS={'Content-Type':'application/json; charset=utf-8'};
function json(data,status=200,extra={}){return new Response(JSON.stringify(data),{status,headers:{...JSON_HEADERS,...extra}})}
function origin(req,env){return env.FRONTEND_ORIGIN || new URL(req.url).origin}
function cors(req,env){const o=origin(req,env);return {'Access-Control-Allow-Origin':o,'Access-Control-Allow-Credentials':'true','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS','Vary':'Origin'}}
function okJson(req,env,data,status=200){return json(data,status,cors(req,env))}
function now(){return new Date().toISOString().slice(0,19)}
function ext(name=''){const m=name.toLowerCase().match(/\.[a-z0-9]+$/);return m?m[0]:'.bin'}
function encKey(key){return key.split('/').map(encodeURIComponent).join('/')}
function imageUrl(filename,req,env){if(!filename)return ''; if(/^https?:\/\//i.test(filename))return filename; if(filename.startsWith('/img/')||filename.startsWith('/uploads/'))return origin(req,env)+filename; if(filename.startsWith('r2/'))return new URL('/r2/'+encKey(filename.slice(3)),req.url).toString(); return new URL('/r2/'+encKey('works/'+filename),req.url).toString()}
function publicWork(r,req,env){const d={...r};d.main_image=imageUrl(d.main_image,req,env);return d}
async function passwordHash(password){const salt=crypto.getRandomValues(new Uint8Array(16));const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt,iterations:600000,hash:'SHA-256'},key,256);return `pbkdf2:sha256:600000$${hex(salt)}$${hex(new Uint8Array(bits))}`}
function hex(a){return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
function bytes(h){const a=new Uint8Array(h.length/2);for(let i=0;i<a.length;i++)a[i]=parseInt(h.slice(i*2,i*2+2),16);return a}
async function passwordCheck(password,stored){try{const m=/^pbkdf2:sha256:(\d+)\$([0-9a-f]+)\$([0-9a-f]+)$/i.exec(stored||'');if(!m)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:bytes(m[2]),iterations:Number(m[1]),hash:'SHA-256'},key,bytes(m[3]).length*8);return hex(new Uint8Array(bits)).toLowerCase()===m[3].toLowerCase()}catch{return false}}
async function admin(req,env){const h=req.headers.get('Authorization')||'';if(!h.startsWith('Bearer '))return null;const token=h.slice(7);const s=await env.DB.prepare('SELECT s.token,s.admin_id,s.expires_at,a.username,a.role,a.display_name FROM sessions s JOIN admins a ON a.id=s.admin_id WHERE s.token=?').bind(token).first();if(!s||Number(s.expires_at)<Date.now()){if(s)await env.DB.prepare('DELETE FROM sessions WHERE token=?').bind(token).run();return null}return s}
async function requireAdmin(req,env){const a=await admin(req,env);return a}
async function log(env,a,action,detail=''){try{await env.DB.prepare('INSERT INTO operation_logs(admin_id,admin_name,action,detail,created_at) VALUES(?,?,?,?,?)').bind(a?.admin_id||null,a?.display_name||a?.username||'管理员',action,detail,now()).run()}catch{}}
function parseSocial(raw){let s={微博:'',抖音:'',公众号:''};try{const x=JSON.parse(raw||'{}');if(Array.isArray(x)){s.微博=x[0]||'';s.抖音=x[1]||'';s.公众号=x[2]||''}else if(x){s={微博:x.微博||'',抖音:x.抖音||'',公众号:x.公众号||''}}}catch{}return s}
async function uploadFile(env,file,folder){if(!file||typeof file.arrayBuffer!=='function'||!file.name)return null;const e=ext(file.name);if(!['.jpg','.jpeg','.png','.webp','.gif'].includes(e))throw new Error('仅支持 JPG、JPEG、PNG、WEBP、GIF 图片');const key=`${folder}/${crypto.randomUUID()}${e}`;await env.BUCKET.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||'application/octet-stream',cacheControl:'public, max-age=31536000'}});return 'r2/'+key}
function periodList(min,max){if(!Number.isFinite(min)||!Number.isFinite(max)||min>max)return[];const out=[];let s=min;while(s<=max){const e=Math.min(Math.floor(s/10)*10+9,max);out.push(`${s}-${e}`);s=e+1}return out}
async function range(env){const {results}=await env.DB.prepare("SELECT creation_time FROM works WHERE creation_time IS NOT NULL AND TRIM(creation_time)<>''").all();const ys=results.map(x=>Number(x.creation_time)).filter(y=>Number.isInteger(y)&&y>0&&y<=new Date().getFullYear());if(!ys.length){const y=new Date().getFullYear();return {min_year:y,max_year:y,has_data:false}}return {min_year:Math.min(...ys),max_year:Math.max(...ys),has_data:true}}
async function router(req,env){const u=new URL(req.url),p=u.pathname;if(p==='/api/admin/login'&&req.method==='POST'){const d=await req.json();const username=(d.username||'').trim(),password=d.password||'';const r=await env.DB.prepare('SELECT * FROM admins WHERE username=?').bind(username).first();if(!r||!(await passwordCheck(password,r.password_hash)))return okJson(req,env,{ok:false,message:'账号或密码错误'},401);const token=crypto.randomUUID()+crypto.randomUUID().replaceAll('-','');await env.DB.prepare('INSERT INTO sessions(token,admin_id,expires_at) VALUES(?,?,?)').bind(token,r.id,Date.now()+7*86400000).run();const a={admin_id:r.id,username:r.username,role:r.role,display_name:r.display_name};await log(env,a,'登录','管理员登录');return okJson(req,env,{ok:true,token,admin:r.display_name||r.username,role:r.role})}
if(p==='/api/admin/logout'&&req.method==='POST'){const a=await admin(req,env);if(a){await log(env,a,'退出登录','管理员退出登录');await env.DB.prepare('DELETE FROM sessions WHERE admin_id=?').bind(a.admin_id).run()}return okJson(req,env,{ok:true})}
if(p==='/api/site'&&req.method==='GET'){const r=await env.DB.prepare('SELECT * FROM site_config WHERE id=1').first();return okJson(req,env,r||{})}
if(p==='/api/home/random'&&req.method==='GET'){const {results}=await env.DB.prepare('SELECT w.*,c.name category,sc.name subcategory FROM works w LEFT JOIN categories c ON c.id=w.category_id LEFT JOIN subcategories sc ON sc.id=w.subcategory_id ORDER BY RANDOM() LIMIT 12').all();return okJson(req,env,results.map(x=>publicWork(x,req,env)))}
if(p==='/api/categories'&&req.method==='GET'){const {results}=await env.DB.prepare('SELECT id,name FROM categories ORDER BY id').all();for(const r of results){const x=await env.DB.prepare('SELECT id,name FROM subcategories WHERE category_id=? ORDER BY id').bind(r.id).all();r.subs=x.results.map(y=>y.name);r.subitems=x.results}return okJson(req,env,results)}
if(p==='/api/periods'&&req.method==='GET'){const x=await env.DB.prepare('SELECT * FROM periods ORDER BY id').all();return okJson(req,env,x.results)}
if(p==='/api/creation-time-range'&&req.method==='GET')return okJson(req,env,await range(env))
if(p==='/api/works'&&req.method==='GET'){const page=Math.max(1,Number(u.searchParams.get('page')||1)),size=Math.min(100,Math.max(1,Number(u.searchParams.get('size')||20))),kw=(u.searchParams.get('keyword')||'').trim(),cat=(u.searchParams.get('category')||'').trim(),sub=(u.searchParams.get('subcategory')||'').trim(),period=(u.searchParams.get('period')||'').trim(),tm=(u.searchParams.get('time_min')||'').trim(),tx=(u.searchParams.get('time_max')||'').trim();let wh=[],args=[];if(kw){wh.push('(w.name LIKE ? OR w.work_no LIKE ? OR w.description LIKE ?)');args.push(`%${kw}%`,`%${kw}%`,`%${kw}%`)}if(cat){wh.push('c.name=?');args.push(cat)}if(sub){wh.push('sc.name=?');args.push(sub)}if(period){wh.push('CAST(w.creation_time AS INTEGER) BETWEEN ? AND ?');args.push(Number(period.split('-')[0]),Number(period.split('-')[1]))}if(tm){wh.push('CAST(w.creation_time AS INTEGER)>=?');args.push(Number(tm))}if(tx){wh.push('CAST(w.creation_time AS INTEGER)<=?');args.push(Number(tx))}const where=wh.length?' WHERE '+wh.join(' AND '):'';const total=(await env.DB.prepare(`SELECT COUNT(*) n FROM works w LEFT JOIN categories c ON c.id=w.category_id LEFT JOIN subcategories sc ON sc.id=w.subcategory_id${where}`).bind(...args).first()).n;const q=await env.DB.prepare(`SELECT w.*,c.name category,sc.name subcategory FROM works w LEFT JOIN categories c ON c.id=w.category_id LEFT JOIN subcategories sc ON sc.id=w.subcategory_id${where} ORDER BY w.id DESC LIMIT ? OFFSET ?`).bind(...args,size,(page-1)*size).all();return okJson(req,env,{items:q.results.map(x=>publicWork(x,req,env)),total,page,size,pages:Math.ceil(total/size)})}
if(p.startsWith('/api/works/')&&req.method==='GET'){const id=Number(p.split('/').pop());const r=await env.DB.prepare('SELECT w.*,c.name category,sc.name subcategory FROM works w LEFT JOIN categories c ON c.id=w.category_id LEFT JOIN subcategories sc ON sc.id=w.subcategory_id WHERE w.id=?').bind(id).first();if(!r)return okJson(req,env,{message:'作品不存在'},404);const imgs=await env.DB.prepare('SELECT * FROM work_images WHERE work_id=? ORDER BY id').bind(id).all();r.main_image=imageUrl(r.main_image,req,env);r.images=imgs.results.map(x=>({id:x.id,url:imageUrl(x.filename,req,env),is_main:!!x.is_main}));return okJson(req,env,r)}
const a=await requireAdmin(req,env);if(p.startsWith('/api/admin/')&&!a)return okJson(req,env,{message:'请先登录'},401);
if(p==='/api/admin/status'&&req.method==='GET'){const w=await env.DB.prepare('SELECT COUNT(*) n FROM works').first(),i=await env.DB.prepare('SELECT COUNT(*) n FROM work_images').first(),c=await env.DB.prepare('SELECT COUNT(*) n FROM categories').first();return okJson(req,env,{ok:true,database:0,counts:{works:w.n,images:i.n,categories:c.n},cloud:'Cloudflare D1 + R2',port:'cloud',admin:a.display_name||a.username,role:a.role})}
if(p==='/api/admin/logs'&&req.method==='GET'){const page=Math.max(1,Number(u.searchParams.get('page')||1)),size=20;let where=a.role==='super'?'':' WHERE admin_id NOT IN (SELECT id FROM admins WHERE role=\'super\')';const total=(await env.DB.prepare(`SELECT COUNT(*) n FROM operation_logs${where}`).first()).n;const q=await env.DB.prepare(`SELECT * FROM operation_logs${where} ORDER BY id DESC LIMIT ? OFFSET ?`).bind(size,(page-1)*size).all();return okJson(req,env,{items:q.results,total,page,pages:Math.ceil(total/size)})}
if(p==='/api/admin/admins'&&req.method==='GET'){if(a.role!=='super')return okJson(req,env,{message:'只有超级管理员可以管理管理员'},403);const q=await env.DB.prepare('SELECT id,username,role,display_name,created_at,updated_at FROM admins ORDER BY id').all();return okJson(req,env,q.results)}
if(/^\/api\/admin\/admins\/\d+$/.test(p)){if(a.role!=='super')return okJson(req,env,{message:'只有超级管理员可以管理管理员'},403);const id=Number(p.split('/').pop());if(req.method==='GET'){const r=await env.DB.prepare('SELECT id,username,role,display_name,created_at,updated_at FROM admins WHERE id=?').bind(id).first();return r?okJson(req,env,r):okJson(req,env,{message:'管理员不存在'},404)}if(req.method==='PUT'){const d=await req.json(),r=await env.DB.prepare('SELECT * FROM admins WHERE id=?').bind(id).first();if(!r)return okJson(req,env,{message:'管理员不存在'},404);let role=d.role==='super'||d.role==='admin'?d.role:'admin',username=(d.username||'').trim(),display=(d.display_name||'').trim();if(r.username==='admin'){role='super';display='超级管理员'}if(id===a.admin_id&&role!=='super')return okJson(req,env,{message:'超级管理员不能取消自己的超级管理员权限'},400);if(!username)return okJson(req,env,{message:'账号不能为空'},400);try{if(d.password){if(d.password.length<6)return okJson(req,env,{message:'密码至少6位'},400);await env.DB.prepare('UPDATE admins SET username=?,password_hash=?,role=?,display_name=?,updated_at=? WHERE id=?').bind(username,await passwordHash(d.password),role,display||username,now(),id).run()}else await env.DB.prepare('UPDATE admins SET username=?,role=?,display_name=?,updated_at=? WHERE id=?').bind(username,role,display||username,now(),id).run();await log(env,a,'编辑管理员',`管理员ID：${id}，账号：${username}`);return okJson(req,env,{ok:true})}catch(e){return okJson(req,env,{ok:false,message:'账号已存在或保存失败'},400)}}if(req.method==='DELETE'){if(id===a.admin_id)return okJson(req,env,{ok:false,message:'不能删除当前登录管理员'},400);const r=await env.DB.prepare('SELECT username,role FROM admins WHERE id=?').bind(id).first();if(!r)return okJson(req,env,{ok:false,message:'管理员不存在'},404);if(r.role==='super'&&Number((await env.DB.prepare("SELECT COUNT(*) n FROM admins WHERE role='super'").first()).n)<=1)return okJson(req,env,{ok:false,message:'至少保留一名超级管理员'},400);await env.DB.prepare('DELETE FROM admins WHERE id=?').bind(id).run();await log(env,a,'删除管理员',`管理员ID：${id}，账号：${r.username}`);return okJson(req,env,{ok:true})}}
if(p==='/api/admin/admins'&&req.method==='POST'){if(a.role!=='super')return okJson(req,env,{message:'只有超级管理员可以管理管理员'},403);const d=await req.json(),username=(d.username||'').trim(),password=d.password||'',display=(d.display_name||'').trim(),role=d.role==='super'?'super':'admin';if(!username||password.length<6)return okJson(req,env,{message:'账号和密码不能为空，密码至少6位'},400);try{const r=await env.DB.prepare('INSERT INTO admins(username,password_hash,role,display_name,created_at,updated_at) VALUES(?,?,?,?,?,?)').bind(username,await passwordHash(password),role,display||username,now(),now()).run();await log(env,a,'新增管理员',`管理员ID：${r.meta.last_row_id}，账号：${username}`);return okJson(req,env,{ok:true,id:r.meta.last_row_id})}catch{return okJson(req,env,{message:'账号已存在'},400)}}
if(p==='/api/admin/site'&&req.method==='POST'){const fd=await req.formData(),site=(fd.get('site_name')||'').trim(),artist=(fd.get('artist_name')||'').trim();if(!site)return okJson(req,env,{message:'站点名称不能为空'},400);if([...site].length>20||[...artist].length>20)return okJson(req,env,{message:'名称最多20个字'},400);const old=await env.DB.prepare('SELECT * FROM site_config WHERE id=1').first();let avatar=old?.avatar||'',logo=old?.logo||'';if(fd.get('avatar')?.name)avatar=await uploadFile(env,fd.get('avatar'),'site');if(fd.get('logo')?.name)logo=await uploadFile(env,fd.get('logo'),'site');await env.DB.prepare('UPDATE site_config SET site_name=?,logo=?,avatar=?,artist_name=?,artist_bio=?,social_links=? WHERE id=1').bind(site,logo,avatar,artist,fd.get('artist_bio')||'',fd.get('social_links')||'{}').run();await log(env,a,'站点配置','修改站点信息');return okJson(req,env,{ok:true,logo:imageUrl(logo,req,env),avatar:imageUrl(avatar,req,env)})}
if(/^\/api\/admin\/works(?:\/\d+)?$/.test(p)){const idMatch=p.match(/\d+$/);const id=idMatch?Number(idMatch[0]):null;if(req.method==='POST'&&id===null||req.method==='PUT'&&id!==null){const fd=await req.formData(),name=(fd.get('name')||'').trim(),cat=Number(fd.get('category_id')||0),sub=fd.get('subcategory_id')?Number(fd.get('subcategory_id')):null;if(!name||!cat)return okJson(req,env,{message:'作品名称和作品分类不能为空'},400);if(sub&&!(await env.DB.prepare('SELECT 1 FROM subcategories WHERE id=? AND category_id=?').bind(sub,cat).first()))return okJson(req,env,{message:'所选细分类与一级分类不匹配'},400);const files=fd.getAll('images').filter(x=>x&&x.name);if(files.length>20)return okJson(req,env,{message:'单件作品最多上传20张图片'},400);if(id===null){const d={name,category_id:cat,subcategory_id:sub,work_no:(fd.get('work_no')||'').trim()||null,creation_time:(fd.get('creation_time')||'').trim(),size:(fd.get('size')||'').trim(),description:fd.get('description')||'',created_at:now()};try{const r=await env.DB.prepare('INSERT INTO works(name,category_id,subcategory_id,work_no,creation_time,size,description,main_image,created_at) VALUES(?,?,?,?,?,?,?,?,?)').bind(d.name,d.category_id,d.subcategory_id,d.work_no,d.creation_time,d.size,d.description,null,d.created_at).run();const wid=r.meta.last_row_id;let first=null;for(const f of files){const key=await uploadFile(env,f,'works');if(!first)first=key;await env.DB.prepare('INSERT INTO work_images(work_id,filename,is_main) VALUES(?,?,?)').bind(wid,key,first===key?1:0).run()}if(first)await env.DB.prepare('UPDATE works SET main_image=? WHERE id=?').bind(first,wid).run();await log(env,a,'新增作品',`作品ID：${wid}，作品名称：${name}，上传图片：${files.length}张`);return okJson(req,env,{ok:true,id:wid,uploaded:files.length})}catch(e){return okJson(req,env,{message:'作品保存失败：'+e.message},500)}}
const old=await env.DB.prepare('SELECT * FROM works WHERE id=?').bind(id).first();if(!old)return okJson(req,env,{message:'作品不存在'},404);const cnt=Number((await env.DB.prepare('SELECT COUNT(*) n FROM work_images WHERE work_id=?').bind(id).first()).n);if(cnt+files.length>20)return okJson(req,env,{message:`单件作品最多20张图片，当前已有${cnt}张，最多还可上传${20-cnt}张`},400);try{await env.DB.prepare('UPDATE works SET name=?,category_id=?,subcategory_id=?,work_no=?,creation_time=?,size=?,description=? WHERE id=?').bind(name,cat,sub,(fd.get('work_no')||'').trim()||null,(fd.get('creation_time')||'').trim(),(fd.get('size')||'').trim(),fd.get('description')||'',id).run();let first=null;for(const f of files){const key=await uploadFile(env,f,'works');if(!first)first=key;await env.DB.prepare('INSERT INTO work_images(work_id,filename,is_main) VALUES(?,?,0)').bind(id,key).run()}if(first&&!old.main_image){await env.DB.prepare('UPDATE work_images SET is_main=1 WHERE work_id=? AND filename=?').bind(id,first).run();await env.DB.prepare('UPDATE works SET main_image=? WHERE id=?').bind(first,id).run()}await log(env,a,'编辑作品',`作品ID：${id}，作品名称：${name}，新增图片：${files.length}张`);return okJson(req,env,{ok:true,id,uploaded:files.length})}catch(e){return okJson(req,env,{message:'作品保存失败：'+e.message},500)}}
if(req.method==='DELETE'&&id!==null){const imgs=await env.DB.prepare('SELECT filename FROM work_images WHERE work_id=?').bind(id).all();const row=await env.DB.prepare('SELECT name FROM works WHERE id=?').bind(id).first();await env.DB.prepare('DELETE FROM work_images WHERE work_id=?').bind(id).run();await env.DB.prepare('DELETE FROM works WHERE id=?').bind(id).run();for(const x of imgs.results){if(String(x.filename).startsWith('r2/'))await env.BUCKET.delete(x.filename.slice(3))}await log(env,a,'删除作品',`作品ID：${id}，作品名称：${row?.name||''}`);return okJson(req,env,{ok:true})}}
if(/^\/api\/admin\/works\/\d+\/main-image$/.test(p)&&req.method==='POST'){const wid=Number(p.split('/')[4]),d=await req.json(),iid=Number(d.image_id);const r=await env.DB.prepare('SELECT filename FROM work_images WHERE id=? AND work_id=?').bind(iid,wid).first();if(!r)return okJson(req,env,{message:'图片不存在'},404);await env.DB.prepare('UPDATE work_images SET is_main=0 WHERE work_id=?').bind(wid).run();await env.DB.prepare('UPDATE work_images SET is_main=1 WHERE id=?').bind(iid).run();await env.DB.prepare('UPDATE works SET main_image=? WHERE id=?').bind(r.filename,wid).run();await log(env,a,'设置主图',`作品ID：${wid}，图片ID：${iid}`);return okJson(req,env,{ok:true})}
if(/^\/api\/admin\/works\/\d+\/images\/\d+$/.test(p)&&req.method==='DELETE'){const parts=p.split('/'),wid=Number(parts[4]),iid=Number(parts[6]);const r=await env.DB.prepare('SELECT filename,is_main FROM work_images WHERE id=? AND work_id=?').bind(iid,wid).first();if(!r)return okJson(req,env,{message:'图片不存在'},404);const cnt=Number((await env.DB.prepare('SELECT COUNT(*) n FROM work_images WHERE work_id=?').bind(wid).first()).n);if(cnt<=1)return okJson(req,env,{message:'至少保留一张作品图片'},400);await env.DB.prepare('DELETE FROM work_images WHERE id=?').bind(iid).run();if(r.is_main){const n=await env.DB.prepare('SELECT id,filename FROM work_images WHERE work_id=? ORDER BY id LIMIT 1').bind(wid).first();await env.DB.prepare('UPDATE work_images SET is_main=1 WHERE id=?').bind(n.id).run();await env.DB.prepare('UPDATE works SET main_image=? WHERE id=?').bind(n.filename,wid).run()}if(String(r.filename).startsWith('r2/'))await env.BUCKET.delete(r.filename.slice(3));await log(env,a,'删除作品图片',`作品ID：${wid}，图片ID：${iid}`);return okJson(req,env,{ok:true})}
if(p==='/api/admin/works/batch-delete'&&req.method==='POST'){const d=await req.json(),ids=[...new Set((d.ids||[]).map(Number).filter(Number.isFinite))];if(!ids.length)return okJson(req,env,{message:'请先选择要删除的作品'},400);const ph=ids.map(()=>'?').join(','),rows=await env.DB.prepare(`SELECT id,name FROM works WHERE id IN (${ph})`).bind(...ids).all();const imgs=await env.DB.prepare(`SELECT filename FROM work_images WHERE work_id IN (${ph})`).bind(...ids).all();await env.DB.prepare(`DELETE FROM work_images WHERE work_id IN (${ph})`).bind(...ids).run();await env.DB.prepare(`DELETE FROM works WHERE id IN (${ph})`).bind(...ids).run();for(const x of imgs.results){if(String(x.filename).startsWith('r2/'))await env.BUCKET.delete(x.filename.slice(3))}await log(env,a,'批量删除作品',`删除${rows.results.length}件作品`);return okJson(req,env,{ok:true,deleted:rows.results.length})}
if(p==='/api/admin/categories'&&req.method==='POST'){const d=await req.json();try{const r=await env.DB.prepare('INSERT INTO categories(name) VALUES(?)').bind((d.name||'').trim()).run();await log(env,a,'新增一级分类',`分类：${d.name}`);return okJson(req,env,{ok:true,id:r.meta.last_row_id})}catch{return okJson(req,env,{message:'分类名称已存在'},400)}}
if(p==='/api/admin/subcategories'&&req.method==='POST'){const d=await req.json();try{const r=await env.DB.prepare('INSERT INTO subcategories(category_id,name) VALUES(?,?)').bind(d.category_id,(d.name||'').trim()).run();await log(env,a,'新增二级分类',`分类ID：${d.category_id}，名称：${d.name}`);return okJson(req,env,{ok:true,id:r.meta.last_row_id})}catch{return okJson(req,env,{message:'二级分类名称已存在'},400)}}
if(/^\/api\/admin\/categories\/\d+$/.test(p)){const id=Number(p.split('/').pop());if(req.method==='PUT'){const d=await req.json();try{await env.DB.prepare('UPDATE categories SET name=? WHERE id=?').bind((d.name||'').trim(),id).run();await log(env,a,'编辑一级分类',`分类ID：${id}`);return okJson(req,env,{ok:true})}catch{return okJson(req,env,{message:'分类名称已存在'},400)}}if(req.method==='DELETE'){const sub=Number((await env.DB.prepare('SELECT COUNT(*) n FROM subcategories WHERE category_id=?').bind(id).first()).n),used=Number((await env.DB.prepare('SELECT COUNT(*) n FROM works WHERE category_id=?').bind(id).first()).n);if(sub||used)return okJson(req,env,{message:'该分类正在使用，不能删除'},400);await env.DB.prepare('DELETE FROM categories WHERE id=?').bind(id).run();await log(env,a,'删除一级分类',`分类ID：${id}`);return okJson(req,env,{ok:true})}}
if(/^\/api\/admin\/subcategories\/\d+$/.test(p)){const id=Number(p.split('/').pop());if(req.method==='PUT'){const d=await req.json();try{await env.DB.prepare('UPDATE subcategories SET name=? WHERE id=?').bind((d.name||'').trim(),id).run();await log(env,a,'编辑二级分类',`分类ID：${id}`);return okJson(req,env,{ok:true})}catch{return okJson(req,env,{message:'二级分类名称已存在'},400)}}if(req.method==='DELETE'){const used=Number((await env.DB.prepare('SELECT COUNT(*) n FROM works WHERE subcategory_id=?').bind(id).first()).n);if(used)return okJson(req,env,{message:'该二级分类正在使用，不能删除'},400);await env.DB.prepare('DELETE FROM subcategories WHERE id=?').bind(id).run();await log(env,a,'删除二级分类',`分类ID：${id}`);return okJson(req,env,{ok:true})}}
return okJson(req,env,{message:'接口不存在'},404)}
export default {async fetch(req,env){if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req,env)});const u=new URL(req.url);if(u.pathname.startsWith('/r2/')){const key=decodeURIComponent(u.pathname.slice(4));const o=await env.BUCKET.get(key);if(!o)return new Response('Not found',{status:404});const h=new Headers(cors(req,env));o.writeHttpMetadata(h);h.set('etag',o.httpEtag);return new Response(o.body,{headers:h})}try{return await router(req,env)}catch(e){return okJson(req,env,{message:'服务器错误：'+e.message},500)}}};
